# Generated by Django 3.2.7 on 2021-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteor',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meteor',
            name='weight',
            field=models.FloatField(max_length=7),
        ),
    ]
